### ISSUE TITLE
Unhandled Execution in Script

### ISSUE THREAD

**Issue by KingGamingYT** [weegeeday/Jackbox-sti-script#3]
**Describe the bug**
After trying to replace images, the application hangs, and after a while, this pops up.

![image](https://user-images.githubusercontent.com/45918062/197678313-5a3f3689-6c7c-443d-913f-4fb41da2fdc4.png)
![image](https://user-images.githubusercontent.com/45918062/197678330-b838b1df-8e63-4de2-9ab8-d8d6389ef5af.png)

**Comment by weegeeday** [comment]
Can you please download the source code and follow the instructions in the readme?
After that reply what text is in the console. Thank you!

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/197679445-90ed41a3-0955-4ed2-abf0-c18f9e7b4d1e.png)
![image](https://user-images.githubusercontent.com/45918062/197679501-5eb97b08-6d2f-4fce-95a1-d860e65d77c1.png)

**Comment by weegeeday** [comment]
Run this:
py -m pip install pysimplegui
py -m pip install Pillow
py -m pip install vdf
And then py GUI.py
Might fix it
As before, post console output.

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/197680374-c6fdee2c-4dcf-44be-baea-7eb83a2ad8e4.png)
Same story, lemme check my PATH.

**Comment by weegeeday** [comment]
Try running GUI.py like this:
py GUI.py

**Comment by KingGamingYT** [comment]
![image](https://user-images.githubusercontent.com/45918062/197680778-113a9f0c-4966-49cd-bb8a-44a30b3be593.png)
then it opens the application

**Comment by weegeeday** [comment]
Odd. Seems to be a python library issue, so il have to check my setup.bat script and such. At least it now works!

**Comment by weegeeday** [comment]
Gonna leave this open until tomorrow. Just in case more errors occur.

**Comment by KingGamingYT** [comment]
The program went off without a hitch this time, I guess it was just some config error with the standalone app. Thanks for the snappy help since it's midnight here!

**Comment by weegeeday** [comment]
Same time here, no problem! Il have to check some of the autobuild options maybe.
Il be closing the issue now at everything works. Have a nice night!
