### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement json (from versions: none)

### ISSUE THREAD

**Issue by modestonom** [weegeeday/Jackbox-sti-script#7]
![imagem_2024-05-05_133459340](https://github.com/weegeeday/Jackbox-sti-script/assets/154757482/365cb86c-c4c1-4c99-b1e4-c91f88f8496b)

**Comment by weegeeday** [comment]
might of been an accident, but if the app still boots it should be fine.
all the other libs seem ok so it should be fine.
thank you though!

**Comment by weegeeday** [comment]
updated the requirements file.
